name: cd-manual
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMGTAG: ghcr.io/avakarev/lidl-connect-exporter
    steps:
      - uses: actions/checkout@v3
      - id: git
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: ${{ inputs.version }}, latest
          build-args: |
            GITHUB_SHA=${{ steps.git.outputs.sha }}
            GITHUB_REF=${{ inputs.version }}
          push: true
